### ISSUE TITLE
Visibility transition for keyboard accessibility

### ISSUE THREAD

**Issue by samikeijonen** [viljamis/responsive-nav.js#190]
For accessibility keyboard navigation using `Tab`, `Shift + Tab` and `Enter` is important. Responsive Nav handles this well. But I have been wondering small little detail.

User can tab trough the menu items even if the menu is closed and might get lost. This is because menu items get focused even if menu is closed. In other words keyboard user should access menu items only when user opens the menu.

One solution for this would be adding `visibility` transition JS and CSS.

JS:
```js
transition = "max-height " + opts.transition + "ms, visibility " + opts.transition +  "ms linear";
```

CSS:
```css
  .js .nav-collapse {
    visibility: hidden;
  }
  .js .nav-collapse.opened {
    visibility: visible;
  }
```
I usually see this done by using `display: none` and `display: block` but I have not found a way to keep transition when using that. 

When using `visibility` rule you still keep the transition and menu items get focused only when you open the menu.
